### ISSUE TITLE
And if we have multiple? How we can run other simultaneously?

### ISSUE THREAD

**Issue by miguelgargallo** [pinheadmz/handout#12]
[debug] (webserver) Webserver opened at host 207.180.198.58
[debug] (authns) Authoritative Nameserver opened for domain examplenamehere.
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at doListen (node:net:1516:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
user@ip:~/handout$

**Comment by esmiwuals2** [comment]
Multiple? You can't serve more than one domain, use nsd instead, while keeping handout as a zone generator for each domain

**Comment by pinheadmz** [comment]
Yeah, Handout is designed to be very simple and single use: static website on HNS top level domain with https security. For anything more interesting than that, I recommend using "real" tools like nginx, apache, nsd, named etc:

https://en.handypedia.org/wiki/Enable_HTTPS_on_Handshake_domains

However -- you *could* change the port in webserver.js to a custom port and run along side some other webserver.
