### ISSUE TITLE
named-checkzone on generated zone file doesn't pass

### ISSUE THREAD

**Issue by tuxcanfly** [pinheadmz/handout#5]
> named-checkzone test conf/invidious.zone

```
conf/invidious.zone:27: ignoring out-of-zone data (_443._tcp.invidious)
zone test/IN: has 0 SOA records
zone test/IN: has no NS records
zone test/IN: not loaded due to errors.

```

**Comment by pinheadmz** [comment]
It wouldn't surprise me if the zone file was a little buggy, but in this case your syntax isn't quite right:

`named-checkzone <zone name> <zone file>`

i.e.

`named-checkzone indivious conf/indivious.zone`

my local example:

```
--> named-checkzone test-ds conf/test-ds.zone
zone test-ds/IN: loaded serial 1614861687
OK
```

**Comment by tuxcanfly** [comment]
Oh, I thought test was a flag for named-checkzone :facepalm:  Thanks, this works :+1:
