### ISSUE TITLE
DANE

### ISSUE THREAD

**Issue by esmiwuals2** [pinheadmz/handout#6]
$> node lib/handout.js
[debug] (webserver) Webserver opened at host 1.2.3.4
[debug] (authns) Authoritative Nameserver opened for domain example.
(node:17134) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE: address already in use 1.2.3.4:53
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at doListen (net.js:1461:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:17134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17134) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by esmiwuals2** [comment]
Error: listen EADDRINUSE: address already in use 1.2.3.4:53
what can this be?

**Comment by pinheadmz** [comment]
I would make sure that no other software on your computer is bound to port 53 (anything else DNS related?) It's also possible that this error is due to the IP address you chose. You can actually run the hnssec-gen script with `localhost 127.0.0.1` and then actually browse to `https://localhost` with TLS. So I'd say try running it again with 127.0.0.1 if you're just testing locally. If that still doesn't work, look around for other consumers of port 53.

**Comment by esmiwuals2** [comment]
$> dig @127.0.0.1 -p 53 _443._tcp.localhost TLSA +dnssec

; <<>> DiG 9.16.6 <<>> @127.0.0.1 -p 53 _443._tcp.localhost TLSA +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49878
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;_443._tcp.localhost.           IN      TLSA

;; ANSWER SECTION:
_443._tcp.localhost.    3600    IN      TLSA    3 1 1 1626E2CC3359B339D526BB1BF439A73EEFA0B17F3D107B22D03986E7 6802A082
_443._tcp.localhost.    172800  IN      RRSIG   TLSA 8 3 3600 20220917201411 20210916201411 16885 localhost. Oy+KEdZfAdw9zY9buV7NVZ3jwYyny6469THj/jBNbt95qWWIAi7XWQxb O1txayRB6DqduJXOMs64Kflgu2ea2mAMDVa6554Jxek1ruIeOtIniviz jTrTKbjWUFwfHEzireNytfLtkAJfSD0jVvwbkQ13e5iiEhb/Wfoo/kcz SOso/pODxUs4fZFQrMu8eRXWB+sxpEnGnRNoTtRV1eBodv1npTflytSF EI12F7DH8HNEmrpY6JHCdH3DnaUrA9fjHW+rDOciexH13NTjvAf+xoim tup0nuDZqhdK818S24YIvk5YfYR4chMMG+PngS43ZYLgBejlKyeBq3lb Uw8R8Q==

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Sep 17 17:56:21 EDT 2021
;; MSG SIZE  rcvd: 383

**Comment by esmiwuals2** [comment]
test pass?

**Comment by pinheadmz** [comment]
Yeah nice!!!
