### ISSUE TITLE
Remove dot when redirecting from http to https 

### ISSUE THREAD

**Issue by 0xStefan** [pinheadmz/handout#8]
This line
https://github.com/pinheadmz/handout/blob/d98ed370849dbaaeafca77a72aaf6b8741cc3c29/lib/webserver.js#L50

should be changed to
`res.redirect('https://${this.domain}/');`

At least that worked for me.

**Comment by pinheadmz** [comment]
thanks! fixed in https://github.com/pinheadmz/handout/commit/bb79bc8ca956fcb09a6d3a5c666ff7d4c89c00f7
