### ISSUE TITLE
Missing MIME Type

### ISSUE THREAD

**Issue by 0xStefan** [pinheadmz/handout#9]
I think the Content-Type is missing here as a third parameter
https://github.com/pinheadmz/handout/blob/bb79bc8ca956fcb09a6d3a5c666ff7d4c89c00f7/lib/webserver.js#L71

See here
https://github.com/bcoin-org/bweb/blob/98327b4a463a85188db0c5dff75044348febdda2/lib/response.js#L230

I'm getting a bunch of error messages in Chrome with "Content-Type missing"

There is a mime function in bweb used here:
https://github.com/bcoin-org/bweb/blob/98327b4a463a85188db0c5dff75044348febdda2/lib/response.js#L83

but I don't know what's the best way to implement it

**Comment by pinheadmz** [comment]
I'm sure you're right but I'm not able to reproduce, loading my own Handout sites with Chrome -- are there certain file types that throw this error? Or could you give me a link to a handout site you run where this error pops up?

**Comment by 0xStefan** [comment]
For example my Angular app produces script tags with

`<script src="..." type="module">`

The browser will complain and not load the script with the message "Content-Type missing".

**Comment by pinheadmz** [comment]
ok thanks - this fix worked for me, if it works for you too I'll commit:

```diff
diff --git a/lib/webserver.js b/lib/webserver.js
index 6e5817c..779817f 100644
--- a/lib/webserver.js
+++ b/lib/webserver.js
@@ -1,6 +1,7 @@
 'use strict';
 
 const bweb = require('bweb');
+const mime = require('bweb/lib/mime');
 const fs = require('bfile');
 const Path = require('path');
 
@@ -68,7 +69,7 @@ class Webserver {
     } catch (e) {
       code = 404;
     }
-    res.send(code, data);
+    res.send(code, data, mime.file(file));
     this.logger.debug(`${req.socket.remoteAddress} req: ${file} (${code})`);
   }
 }
```

**Comment by 0xStefan** [comment]
Worked for me, too. 👍

**Comment by pinheadmz** [comment]
closed https://github.com/pinheadmz/handout/commit/a0b32ff73f69b34373f42f14f648e7cd8c29b697
